---
- hosts: all
  become: true
  tasks:

    - name: Install Cinder
      apt:
        name:
          - cinder-volume
          - python3-mysqldb
        state: latest

    - name: Install Apache2
      apt:
        name: apache2
        state: latest

    - name: Install Horizon
      apt:
        name:
          - openstack-dashboard
        state: latest

    - name: Install Neutron
      apt:
        name:
          - neutron-server
          - neutron-l3-agent
          - neutron-plugin-ml2
          - neutron-dhcp-agent
          - neutron-linuxbridge-agent
          - python3-neutronclient
        state: latest

    - name: reconfigure Openstack Dashboard Pack
      command: dpkg --configure -a
      ignore_errors: true
